#' Estimation of the AUC of logistic regression models with complex survey data.
#'
#' Calculate the AUC of a logistic regression model
#' considering sampling weights with complex survey data
#' @param response.var Vector with information of the response variable
#' or character string with the name of the variable
#' indicating the response variable in the data set.
#' @param phat.var Vector with information of the estimated probabilities
#' or character string with the name of the variable
#' indicating these probabilities in the data set.
#' @param weights.var Vector with information of the sampling weights
#' or character string with the name of the variable
#' indicating the sampling weights in the data set.
#' If \code{NULL}, the sampling design should be specified in the argument \code{design}.
#' For unweighted estimates, set all the sampling weight values to 1.
#' @param tag.event Label indicating the event of interest in \code{response.var}.
#' The default option is \code{tag.event = NULL}, which selects the class with the lowest number of units.
#' @param tag.nonevent Label indicating the non-event in \code{response.var}.
#' The default option is \code{tag.nonevent = NULL}, which selects the class with the greatest number of units.
#' @param data Data frame which must incorporate information on the columns
#' \code{response.var}, \code{phat.var} and \code{weights.var}.
#' If \code{data=NULL}, then specific numerical vectors must be included in
#' \code{response.var}, \code{phat.var} and \code{weights.var}
#' or the sampling design should be indicated in the argument \code{design}.
#' @param design An object of class \code{survey.design} generated by
#' \code{survey::svydesign} indicating the complex sampling design of the data.
#' If \code{NULL} information on the data and weights must be included in the argument
#' \code{data} or as a vector in the argument \code{weights.var}.
#'
#' @return A numeric value indicating the estimated AUC considering sampling weights

#' @export
#'
#' @examples
#' data(example_data_wroc)
#'
#' auc.obj <- wauc(response.var = "y",
#'                 phat.var = "phat",
#'                 weights.var = "weights",
#'                 tag.event = 1,
#'                 tag.nonevent = 0,
#'                 data = example_data_wroc)
#'
#' # Or equivalently
#' auc.obj <- wauc(response.var = example_data_wroc$y,
#'                 phat.var = example_data_wroc$phat,
#'                 weights.var = example_data_wroc$weights,
#'                 tag.event = 1, tag.nonevent = 0)
#'
wauc <- function(response.var, phat.var, weights.var = NULL, tag.event = NULL, tag.nonevent = NULL, data = NULL, design = NULL){

  if(inherits(response.var, "character")){
    response.var <- data[,response.var]
  }

  if(length(table(response.var))!=2){stop("Response variable must have two classes.")}

  if(inherits(phat.var, "character")){
    phat.var <- data[,phat.var]
  }

  if(inherits(weights.var, "character")){
    weights.var <- data[,weights.var]
  }

  if(!is.null(design)){
    data <- get(design$call$data)
    weights <- as.character(design$call$weights[2])
    weights.var <- data[,weights]
  }

  if(length(response.var) != length(phat.var) || length(response.var) != length(weights.var)){
    stop("Vectors indicating the responses, predicted probabilities and sampling weights must be the same length.")
  }

  # Missing tags:
  if(is.null(tag.nonevent)){
    if(is.null(tag.event)){
      tag.nonevent <- names(table(response.var)[which.max(table(response.var))])
      tag.event <- names(table(response.var)[which.min(table(response.var))])
    } else {
      tags <- names(table(response.var))
      tag.other <- which(tags == tag.event)
      tag.nonevent <- tags[-tag.other]
    }
  } else {
    if(is.null(tag.event)){
      tags <- names(table(response.var))
      tag.other <- which(tags == tag.nonevent)
      tag.event <- tags[-tag.other]
    }
  }


  p0 <- phat.var[which(response.var==tag.nonevent)]
  p1 <- phat.var[which(response.var==tag.event)]

  w0 <- weights.var[which(response.var==tag.nonevent)]
  w1 <- weights.var[which(response.var==tag.event)]

  auc <- (sum(outer(w1, w0, "*")[which(outer(p1, p0, ">"))]) + 0.5*sum(outer(w1, w0, "*")[which(outer(p1, p0, "=="))]))/(sum(w0)*sum(w1))


  auc.obj <- list()
  auc.obj$AUCw <- auc
  auc.obj$tags <- list(tag.event = as.character(tag.event),
                       tag.nonevent = as.character(tag.nonevent))
  auc.obj$basics <- list(n.event = length(which(response.var==tag.event)),
                         n.nonevent = length(which(response.var==tag.nonevent)),
                         hatN.event = sum(w1),
                         hatN.nonevent = sum(w0))
  auc.obj$call <- match.call()


  return(auc.obj)

}


