#' Estimation of the sensitivity with complex survey data
#'
#' Estimate the sensitivity parameter for a given cut-off point
#' considering sampling weights with complex survey data.
#' @param response.var Vector with information of the response variable
#' or character string with the name of the variable
#' indicating the response variable in the data set.
#' @param phat.var Vector with information of the estimated probabilities
#' or character string with the name of the variable
#' indicating these probabilities in the data set.
#' @param weights.var Vector with information of the sampling weights
#' or character string with the name of the variable
#' indicating the sampling weights in the data set.
#' If \code{NULL}, the sampling design should be specified in the argument \code{design}.
#' For unweighted estimates, set all the sampling weight values to 1.
#' @param tag.event Label indicating the event of interest in \code{response.var}.
#' The default option is \code{tag.event = NULL}, which selects the class with the lowest number of units.
#' @param cutoff.value A numeric value indicating the cut-off point to be used.
#' No default value for this argument. A numeric value must be indicated necessarily.
#' @param data Data frame which must incorporate information on the columns
#' \code{response.var}, \code{phat.var} and \code{weights.var}.
#' If \code{data=NULL}, then specific numerical vectors must be included in
#' \code{response.var}, \code{phat.var} and \code{weights.var}
#' or the sampling design should be indicated in the argument \code{design}.
#' @param design An object of class \code{survey.design} generated by
#' \code{survey::svydesign} indicating the complex sampling design of the data.
#' If \code{NULL} information on the data and weights must be included in the argument
#' \code{data} or as a vector in the argument \code{weights.var}.
#' @return The output of this function is a list of 4 elements containing the following information:
#' - `Sew`: a numeric value indicating the weighted estimate of the sensitivity parameter.
#' - `tags`: list containing one element with the following information:
#'    - `tag.event`: a character string indicating the label used to indicate event of interest.
#' - `basics`: a list containing information of the following 6 elements:
#'    - `n`: a numeric value indicating the number of units in the data set.
#'    - `n.event`: a numeric value indicating the number of units in the data set with the event of interest.
#'    - `n.event.class`: a numeric value indicating the number of units in the data set with the event of interest that are correctly classified as events based on the selected cut-off point.
#'    - `hatN`: number of units in the population, represented by all the units in the data set, i.e., the sum of the sampling weights of the units in the data set.
#'    - `hatN.event`: number of units with the event of interest represented in the population by all the event units in the data set, i.e., the sum of the sampling weights of the units with the event of interest in the data set.
#'    - `hatN.event.class`: number of event units represented in the population by the event units in the data set that have been correctly classified as events based on the selected cut-off point, i.e., the sum of the sampling weights of the correctly classified event units in the data set.
#' - `call`: an object saving the information about the way in which the function has been run.
#'
#' @export
#'
#' @examples
#' data(example_data_wroc)
#'
#' se.obj <- wse(response.var = "y", phat.var = "phat", weights.var = "weights",
#'               tag.event = 1, cutoff.value = 0.5, data = example_data_wroc)
#'
#' # Or equivalently
#' se.obj <- wse(response.var = example_data_wroc$y,
#'               phat.var = example_data_wroc$phat,
#'               weights.var = example_data_wroc$weights,
#'               tag.event = 1, cutoff.value = 0.5)
wse <- function(response.var, phat.var, weights.var = NULL, tag.event = NULL, cutoff.value, data = NULL, design = NULL){

  if(missing(cutoff.value) || !is.numeric(cutoff.value)){stop("Please, indicate a numeric value in the 'cutoff.value' argument to be used as cut-off point.")}

  if(inherits(response.var, "character")){
    response.var <- data[,response.var]
  }

  if(length(table(response.var))!=2){stop("Response variable must have two classes.")}

  if(inherits(phat.var, "character")){
    phat.var <- data[,phat.var]
  }

  if(inherits(weights.var, "character")){
    weights.var <- data[,weights.var]
  }

  if(!is.null(design)){
    data <- get(design$call$data)
    weights <- as.character(design$call$weights[2])
    weights.var <- data[,weights]
  }

  if(length(response.var) != length(phat.var) || length(response.var) != length(weights.var)){
    stop("Vectors indicating the responses, predicted probabilities and sampling weights must be the same length.")
  }

  if(is.null(tag.event)){
    tag.event <- names(table(response.var)[which.min(table(response.var))])
  }

  sum.weight <- sum(weights.var[which(response.var == tag.event)])
  yhat.event.w <- sum(weights.var[which(response.var == tag.event & phat.var >= cutoff.value)])

  sew.hat <- yhat.event.w/sum.weight

  sew.obj <- list()

  sew.obj$Sew <- sew.hat
  sew.obj$tags <- list(tag.event = as.character(tag.event))
  sew.obj$basics <- list(n = length(response.var),
                         n.event = length(which(response.var == tag.event)),
                         n.event.class = length(which(response.var == tag.event & phat.var < cutoff.value)),
                         hatN = sum(weights.var),
                         hatN.event = sum.weight,
                         hatN.event.class = yhat.event.w)
  sew.obj$call <- match.call()

  return(sew.obj)

}

